### ISSUE TITLE
SPIKE: solve captcha

### ISSUE THREAD

**Issue by hajonsoft** [hajonsoft/hajonsoft-tiger#287]
Evaluate this third party service https://2captcha.com/ to solve captcha
Also evaluate using tesseract again and train for captchas used by various saudi sites

**Comment by abddeen** [comment]
A colleague of mine uses this puppetteer plugin to solve captcha successfully.
https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-recaptcha

2captcha is a service that uses real people to solve captchas at an affordable price.
@hajonsoft
