### ISSUE TITLE
Download Auto Mofa Number into passenger 

### ISSUE THREAD

**Issue by moulavi** [hajonsoft/hajonsoft-tiger#319]
We have to very difficult Copy paste mofa number way to umra to hajonsoft. 
Kindly update the version Auto Download mofa 

![Screenshot_20220213-072423_Chrome](https://user-images.githubusercontent.com/99552190/153734977-2fbd462d-4ba6-4f0c-abfd-897cb082708e.jpg)

**Comment by hajonsoft** [comment]
https://youtu.be/anOrpfxAEpg
https://user-images.githubusercontent.com/9623964/156898108-e3d05af5-04b2-4805-a860-20a410d20ffd.MOV

https://user-images.githubusercontent.com/9623964/156898112-3c75c1ff-f509-46d0-93e3-3b3c658f2625.MOV

**Comment by hajonsoft** [comment]
There is a better place to get the mofa from 
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/9623964/157524910-23fdbc23-d1f9-40ae-a5c4-f3f0e42260b7.png">


<img width="1401" alt="image" src="https://user-images.githubusercontent.com/9623964/157524960-31eedc55-a26e-433d-8b80-f1526d51a7a0.png">
