### ISSUE TITLE
Simultaneous search in all caravans

### ISSUE THREAD

**Issue by ost2210** [hajonsoft/hajonsoft-tiger#322]
Salam brother,
Please help me to check if some of the passport numbers I have are among the passports registered in the HajOnSoft database.
Is it possible that I can have this global file in excel format?
It is about the caravans whose names end with "Bac".

**Comment by hajonsoft** [comment]
Salam brother Ouattara, We added a global search now. If you look on the top of the navigation bar. Top right. you will see a new search field. You can type the passport number there and it will tell you which caravan this passport number is in
