### ISSUE TITLE
تخزين المعلومات 

### ISSUE THREAD

**Issue by taharparis** [hajonsoft/hajonsoft-tiger#340]
هل ممكن تخزين الصور و صرة التطعيم و صورة الجواز  في الملف C:\Users\admin\hajonsoft  بنفس طريقة تخزين التأشرة

شكرا

**Comment by hajonsoft** [comment]
We can create a photos tab in the caravan details with three buttons
Download all Portrait photos
Download all passport images
Download all vaccine images

**Comment by hajonsoft** [comment]
duplicated
