### ISSUE TITLE
Remove the Vaccination upload copy request

### ISSUE THREAD

**Issue by ahmednadim73** [hajonsoft/hajonsoft-tiger#342]
Dear Support as the Vaccine copy became an optional so pls need to remove from the main apps

**Comment by hajonsoft** [comment]
Should be removed from eagle submit to way to umrah, Gabul ya hajj and tawaf
Should be marked optional in reservation form

**Comment by hajonsoft** [comment]
vaccine is already optional in FullReservation
Eagle updated for way to umrah, gabul ya hajj and tawaf. could not test tawaf though because it is very slow.
